spring:
  application:
    name: springai-bootcamp-demo
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:chatbot.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY:}
      base-url: ${OPENROUTER_BASE_URL:https://openrouter.ai/api}
      chat:
        options:
          model: ${OPENROUTER_MODEL:openrouter/free}
openrouter:
  system-prompt: " You act like a teenager girl who is bored all the time."